### ISSUE TITLE
Change ansible image to not fix dependency versions

### ISSUE THREAD

**Issue by ryanoolala** [GovTechSG/cicd-images#28]
Consider not setting versions of libraries during apk update step for ansible dockerfile

https://github.com/GovTechSG/cicd-images/blob/master/ansible/Dockerfile#L8

https://github.com/GovTechSG/cicd-images/runs/1867778691?check_suite_focus=true

Everytime there is a new library available, the build will fail

**Comment by Salihan04** [comment]
I'll make the changes next week

**Comment by Salihan04** [comment]
Updated the Dockerfile and build is passing for ansible
https://github.com/GovTechSG/cicd-images/runs/1907766269?check_suite_focus=true

Gonna close this issue. For the build failures for dind and gkecli, can open another issue
